window:
  padding:
    x: 10
    y: 10
  dynamic_padding: true
  decorations: full
  title: Alacritty
  dynamic_title: true
  gtk_theme_variant: dark
  opacity: 0.4

font:
  size: 12
  normal:
    family: "JetBrainsMono Nerd Font"
    style: Regular

  bold:
    family: "JetBrainsMono Nerd Font"
    style: Bold

  italic:
    family: "JetBrainsMono Nerd Font"
    style: Italic

  bold_italic:
    family: "JetBrainsMono Nerd Font"
    style: Bold Italic

cursor:
  style:
    shape: Block

colors:
  primary:
    background: '0x181a1f'
    foreground: '0xabb2bf'

  normal:
    black:   '0x181a1f'
    red:     '0xe06c75'
    green:   '0x98c379'
    yellow:  '0xd19a66'
    blue:    '0x61afef'
    magenta: '0xc678dd'
    cyan:    '0x56b6c2'
    white:   '0xabb2bf'
    
  bright:
    black:   '0x5c6370'
    red:     '0xe06c75'
    green:   '0x98c379'
    yellow:  '0xd19a66'
    blue:    '0x61afef'
    magenta: '0xc678dd'
    cyan:    '0x56b6c2'
    white:   '0xffffff'
